import type { TamboComponent } from "@tambo-ai/react";
import {
  AccordionSchema,
  AspectRatioSchema,
  CardSchema,
  CarouselSchema,
  CollapsibleSchema,
  ResizableSchema,
  ScrollAreaSchema,
  SeparatorSchema,
  TabsSchema,
  AvatarSchema,
  BadgeSchema,
  CalendarSchema,
  DataTableSchema,
  TableSchema,
  TypographySchema,
  SkeletonSchema,
  KbdSchema,
  ButtonSchema,
  CheckboxSchema,
  InputSchema,
  InputOTPSchema,
  LabelSchema,
  RadioGroupSchema,
  SelectSchema,
  SliderSchema,
  SwitchSchema,
  TextareaSchema,
  ToggleSchema,
  ToggleGroupSchema,
  AlertSchema,
  ProgressSchema,
  TooltipSchema,
  SpinnerSchema,
  SonnerSchema,
  BreadcrumbSchema,
  MenubarSchema,
  NavigationMenuSchema,
  PaginationSchema,
  DropdownMenuSchema,
  AlertDialogSchema,
  CommandSchema,
  ContextMenuSchema,
  DialogSchema,
  DrawerSchema,
  HoverCardSchema,
  PopoverSchema,
  SheetSchema,
  ChartSchema,
} from "@/lib/tambo/schemas";

import {
  TamboAccordion,
  TamboAspectRatio,
  TamboCard,
  TamboCarousel,
  TamboCollapsible,
  TamboResizable,
  TamboScrollArea,
  TamboSeparator,
  TamboTabs,
  TamboAvatar,
  TamboBadge,
  TamboCalendar,
  TamboDataTable,
  TamboTable,
  TamboTypography,
  TamboSkeleton,
  TamboKbd,
  TamboButton,
  TamboCheckbox,
  TamboInput,
  TamboInputOTP,
  TamboLabel,
  TamboRadioGroup,
  TamboSelect,
  TamboSlider,
  TamboSwitch,
  TamboTextarea,
  TamboToggle,
  TamboToggleGroup,
  TamboAlert,
  TamboProgress,
  TamboTooltip,
  TamboSpinner,
  TamboSonner,
  TamboBreadcrumb,
  TamboMenubar,
  TamboNavigationMenu,
  TamboPagination,
  TamboDropdownMenu,
  TamboAlertDialog,
  TamboCommand,
  TamboContextMenu,
  TamboDialog,
  TamboDrawer,
  TamboHoverCard,
  TamboPopover,
  TamboSheet,
  TamboChart,
} from "./wrappers";

export const tamboComponents: TamboComponent[] = [
  // High priority - most useful for rendering GraphQL data
  {
    name: "DataTable",
    description:
      "A dynamic data table with columns and rows. Best for displaying structured query results with multiple fields. Use this as the primary way to show lists of records from GraphQL queries.",
    component: TamboDataTable,
    propsSchema: DataTableSchema,
  },
  {
    name: "Card",
    description:
      "A card component for grouped content with title, description, body, and footer. Great for showing individual record details or summaries.",
    component: TamboCard,
    propsSchema: CardSchema,
  },
  {
    name: "Chart",
    description:
      "A chart component supporting bar, line, area, pie, and radar chart types. Use for visualizing numeric data from GraphQL queries.",
    component: TamboChart,
    propsSchema: ChartSchema,
  },
  {
    name: "Table",
    description:
      "A simple table with headers and rows as string arrays. Use for quick tabular display when you have simple string data.",
    component: TamboTable,
    propsSchema: TableSchema,
  },
  {
    name: "Alert",
    description:
      "An alert component for displaying important messages, errors, or status information.",
    component: TamboAlert,
    propsSchema: AlertSchema,
  },
  {
    name: "Typography",
    description:
      "Typography component for rendering styled text in various sizes from h1 to muted small text.",
    component: TamboTypography,
    propsSchema: TypographySchema,
  },
  {
    name: "Badge",
    description:
      "A small badge for displaying status labels, tags, or counts.",
    component: TamboBadge,
    propsSchema: BadgeSchema,
  },
  {
    name: "Tabs",
    description:
      "Tabbed content panels. Great for organizing different views of data or grouping related information.",
    component: TamboTabs,
    propsSchema: TabsSchema,
  },
  {
    name: "Accordion",
    description:
      "Collapsible accordion sections for organizing content into expandable items.",
    component: TamboAccordion,
    propsSchema: AccordionSchema,
  },

  // Layout
  {
    name: "AspectRatio",
    description: "Maintains a consistent aspect ratio for content.",
    component: TamboAspectRatio,
    propsSchema: AspectRatioSchema,
  },
  {
    name: "Carousel",
    description:
      "A carousel for cycling through items horizontally or vertically.",
    component: TamboCarousel,
    propsSchema: CarouselSchema,
  },
  {
    name: "Collapsible",
    description: "A collapsible section with a trigger to show/hide content.",
    component: TamboCollapsible,
    propsSchema: CollapsibleSchema,
  },
  {
    name: "Resizable",
    description: "Resizable panels for flexible layouts.",
    component: TamboResizable,
    propsSchema: ResizableSchema,
  },
  {
    name: "ScrollArea",
    description: "A scrollable area for overflow content.",
    component: TamboScrollArea,
    propsSchema: ScrollAreaSchema,
  },
  {
    name: "Separator",
    description: "A visual separator line between content sections.",
    component: TamboSeparator,
    propsSchema: SeparatorSchema,
  },

  // Data display
  {
    name: "Avatar",
    description: "An avatar component for displaying user profile images.",
    component: TamboAvatar,
    propsSchema: AvatarSchema,
  },
  {
    name: "Calendar",
    description: "A calendar component for displaying dates.",
    component: TamboCalendar,
    propsSchema: CalendarSchema,
  },
  {
    name: "Skeleton",
    description: "A loading skeleton placeholder.",
    component: TamboSkeleton,
    propsSchema: SkeletonSchema,
  },
  {
    name: "Kbd",
    description: "Keyboard key display for showing keyboard shortcuts.",
    component: TamboKbd,
    propsSchema: KbdSchema,
  },

  // Form
  {
    name: "Button",
    description: "A clickable button with various style variants.",
    component: TamboButton,
    propsSchema: ButtonSchema,
  },
  {
    name: "Checkbox",
    description: "A checkbox input with an optional label and description.",
    component: TamboCheckbox,
    propsSchema: CheckboxSchema,
  },
  {
    name: "Input",
    description: "A text input field with an optional label.",
    component: TamboInput,
    propsSchema: InputSchema,
  },
  {
    name: "InputOTP",
    description: "A one-time password input with individual character slots.",
    component: TamboInputOTP,
    propsSchema: InputOTPSchema,
  },
  {
    name: "Label",
    description: "A form label element.",
    component: TamboLabel,
    propsSchema: LabelSchema,
  },
  {
    name: "RadioGroup",
    description: "A group of radio buttons for single selection.",
    component: TamboRadioGroup,
    propsSchema: RadioGroupSchema,
  },
  {
    name: "Select",
    description: "A dropdown select input for choosing from options.",
    component: TamboSelect,
    propsSchema: SelectSchema,
  },
  {
    name: "Slider",
    description: "A slider input for selecting a numeric value.",
    component: TamboSlider,
    propsSchema: SliderSchema,
  },
  {
    name: "Switch",
    description: "A toggle switch with a label.",
    component: TamboSwitch,
    propsSchema: SwitchSchema,
  },
  {
    name: "Textarea",
    description: "A multi-line text input area.",
    component: TamboTextarea,
    propsSchema: TextareaSchema,
  },
  {
    name: "Toggle",
    description: "A toggle button that can be pressed/unpressed.",
    component: TamboToggle,
    propsSchema: ToggleSchema,
  },
  {
    name: "ToggleGroup",
    description: "A group of toggle buttons for single or multiple selection.",
    component: TamboToggleGroup,
    propsSchema: ToggleGroupSchema,
  },

  // Feedback
  {
    name: "Progress",
    description: "A progress bar showing completion percentage.",
    component: TamboProgress,
    propsSchema: ProgressSchema,
  },
  {
    name: "Tooltip",
    description: "A tooltip that shows on hover over a trigger element.",
    component: TamboTooltip,
    propsSchema: TooltipSchema,
  },
  {
    name: "Spinner",
    description: "A loading spinner animation.",
    component: TamboSpinner,
    propsSchema: SpinnerSchema,
  },
  {
    name: "Sonner",
    description: "A toast notification message.",
    component: TamboSonner,
    propsSchema: SonnerSchema,
  },

  // Navigation
  {
    name: "Breadcrumb",
    description: "A breadcrumb navigation trail.",
    component: TamboBreadcrumb,
    propsSchema: BreadcrumbSchema,
  },
  {
    name: "Menubar",
    description: "A horizontal menu bar with dropdown menus.",
    component: TamboMenubar,
    propsSchema: MenubarSchema,
  },
  {
    name: "NavigationMenu",
    description: "A navigation menu with expandable items.",
    component: TamboNavigationMenu,
    propsSchema: NavigationMenuSchema,
  },
  {
    name: "Pagination",
    description: "Page navigation controls for paginated content.",
    component: TamboPagination,
    propsSchema: PaginationSchema,
  },
  {
    name: "DropdownMenu",
    description: "A dropdown menu triggered by a button click.",
    component: TamboDropdownMenu,
    propsSchema: DropdownMenuSchema,
  },

  // Overlay
  {
    name: "AlertDialog",
    description: "A modal dialog for confirmations with confirm/cancel buttons.",
    component: TamboAlertDialog,
    propsSchema: AlertDialogSchema,
  },
  {
    name: "Command",
    description:
      "A command palette with searchable groups of items. Like a spotlight/command-K interface.",
    component: TamboCommand,
    propsSchema: CommandSchema,
  },
  {
    name: "ContextMenu",
    description: "A right-click context menu.",
    component: TamboContextMenu,
    propsSchema: ContextMenuSchema,
  },
  {
    name: "Dialog",
    description: "A modal dialog overlay for displaying content.",
    component: TamboDialog,
    propsSchema: DialogSchema,
  },
  {
    name: "Drawer",
    description: "A drawer panel that slides in from the bottom.",
    component: TamboDrawer,
    propsSchema: DrawerSchema,
  },
  {
    name: "HoverCard",
    description: "A card that appears on hover over a trigger element.",
    component: TamboHoverCard,
    propsSchema: HoverCardSchema,
  },
  {
    name: "Popover",
    description: "A popover panel that appears on click.",
    component: TamboPopover,
    propsSchema: PopoverSchema,
  },
  {
    name: "Sheet",
    description: "A sheet panel that slides in from a side of the screen.",
    component: TamboSheet,
    propsSchema: SheetSchema,
  },
];
